/*
Copyright 2023 The Bestchains Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lordverse/dao/proposal.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProposalStatus int32

const (
	ProposalStatus_PROPOSAL_STATUS_UNSPECIFIED ProposalStatus = 0
	ProposalStatus_PROPOSAL_STATUS_VOTING      ProposalStatus = 1
	ProposalStatus_PROPOSAL_STATUS_SUCCESS     ProposalStatus = 2
	ProposalStatus_PROPOSAL_STATUS_FAILED      ProposalStatus = 3
	ProposalStatus_PROPOSAL_STATUS_CANCELLED   ProposalStatus = 4
	ProposalStatus_PROPOSAL_STATUS_EXPIRED     ProposalStatus = 5
	ProposalStatus_PROPOSAL_STATUS_EXECUTED    ProposalStatus = 6
)

var ProposalStatus_name = map[int32]string{
	0: "PROPOSAL_STATUS_UNSPECIFIED",
	1: "PROPOSAL_STATUS_VOTING",
	2: "PROPOSAL_STATUS_SUCCESS",
	3: "PROPOSAL_STATUS_FAILED",
	4: "PROPOSAL_STATUS_CANCELLED",
	5: "PROPOSAL_STATUS_EXPIRED",
	6: "PROPOSAL_STATUS_EXECUTED",
}

var ProposalStatus_value = map[string]int32{
	"PROPOSAL_STATUS_UNSPECIFIED": 0,
	"PROPOSAL_STATUS_VOTING":      1,
	"PROPOSAL_STATUS_SUCCESS":     2,
	"PROPOSAL_STATUS_FAILED":      3,
	"PROPOSAL_STATUS_CANCELLED":   4,
	"PROPOSAL_STATUS_EXPIRED":     5,
	"PROPOSAL_STATUS_EXECUTED":    6,
}

func (x ProposalStatus) String() string {
	return proto.EnumName(ProposalStatus_name, int32(x))
}

func (ProposalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f96a18dd8ede786, []int{0}
}

type Proposal struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// id of the warehouse
	Warehouse  uint64         `protobuf:"varint,4,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	Expiration *time.Time     `protobuf:"bytes,5,opt,name=expiration,proto3,stdtime" json:"expiration,omitempty"`
	Status     ProposalStatus `protobuf:"varint,6,opt,name=status,proto3,enum=lordverse.dao.ProposalStatus" json:"status,omitempty"`
	Creator    string         `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f96a18dd8ede786, []int{0}
}
func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return m.Size()
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Proposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Proposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Proposal) GetWarehouse() uint64 {
	if m != nil {
		return m.Warehouse
	}
	return 0
}

func (m *Proposal) GetExpiration() *time.Time {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Proposal) GetStatus() ProposalStatus {
	if m != nil {
		return m.Status
	}
	return ProposalStatus_PROPOSAL_STATUS_UNSPECIFIED
}

func (m *Proposal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterEnum("lordverse.dao.ProposalStatus", ProposalStatus_name, ProposalStatus_value)
	proto.RegisterType((*Proposal)(nil), "lordverse.dao.Proposal")
}

func init() { proto.RegisterFile("lordverse/dao/proposal.proto", fileDescriptor_6f96a18dd8ede786) }

var fileDescriptor_6f96a18dd8ede786 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0xac, 0xed, 0xd8, 0x9b, 0xa8, 0x22, 0x6b, 0x80, 0xe9, 0xba, 0x34, 0xe2, 0x54,
	0x71, 0x48, 0xa4, 0x21, 0xee, 0x74, 0xa9, 0x87, 0x22, 0x55, 0x6d, 0x14, 0xa7, 0x08, 0x71, 0x99,
	0xbc, 0xc5, 0x94, 0x48, 0x1d, 0x8e, 0x6c, 0x17, 0xc6, 0x99, 0x2f, 0xb0, 0x8f, 0xc5, 0x71, 0x47,
	0x6e, 0x4c, 0xed, 0x17, 0x41, 0x73, 0x16, 0xb6, 0x95, 0xdd, 0xde, 0x7b, 0xbf, 0xff, 0xff, 0xe9,
	0x9f, 0xf8, 0x41, 0x6f, 0x21, 0x55, 0xfe, 0x4d, 0x28, 0x2d, 0xc2, 0x9c, 0xcb, 0xb0, 0x54, 0xb2,
	0x94, 0x9a, 0x2f, 0x82, 0x52, 0x49, 0x23, 0xf1, 0xd3, 0x7f, 0x34, 0xc8, 0xb9, 0xec, 0xf6, 0xe7,
	0x52, 0xce, 0x17, 0x22, 0xb4, 0xf0, 0x74, 0xf9, 0x39, 0x34, 0xc5, 0xb9, 0xd0, 0x86, 0x9f, 0x97,
	0x95, 0xbe, 0xbb, 0x37, 0x97, 0x73, 0x69, 0xcb, 0xf0, 0xa6, 0xaa, 0xa6, 0xaf, 0x7e, 0x3a, 0xf0,
	0x24, 0xb9, 0x5d, 0x8c, 0x3b, 0xe0, 0x14, 0x39, 0x41, 0x3e, 0x1a, 0x34, 0x53, 0xa7, 0xc8, 0xf1,
	0x1e, 0xb4, 0x4c, 0x61, 0x16, 0x82, 0x38, 0x3e, 0x1a, 0xec, 0xa4, 0x55, 0x83, 0x7d, 0xd8, 0xcd,
	0x85, 0x3e, 0x53, 0x45, 0x69, 0x0a, 0xf9, 0x95, 0x6c, 0x59, 0x76, 0x7f, 0x84, 0x7b, 0xb0, 0xf3,
	0x9d, 0x2b, 0xf1, 0x45, 0x2e, 0xb5, 0x20, 0x4d, 0xbb, 0xee, 0x6e, 0x80, 0xdf, 0x01, 0x88, 0x8b,
	0xb2, 0x50, 0xdc, 0xda, 0x5b, 0x3e, 0x1a, 0xec, 0x1e, 0x76, 0x83, 0x2a, 0x7e, 0x50, 0xc7, 0x0f,
	0xb2, 0x3a, 0xfe, 0x51, 0xf3, 0xf2, 0x4f, 0x1f, 0xa5, 0xf7, 0x3c, 0xf8, 0x2d, 0xb4, 0xb5, 0xe1,
	0x66, 0xa9, 0x49, 0xdb, 0x47, 0x83, 0xce, 0xe1, 0x41, 0xf0, 0xe0, 0x5f, 0x04, 0xf5, 0x07, 0x31,
	0x2b, 0x4a, 0x6f, 0xc5, 0x98, 0xc0, 0xf6, 0x99, 0x12, 0xdc, 0x48, 0x45, 0xb6, 0x6d, 0xe8, 0xba,
	0x7d, 0x7d, 0x8d, 0xa0, 0xf3, 0xd0, 0x84, 0xfb, 0xb0, 0x9f, 0xa4, 0xd3, 0x64, 0xca, 0x86, 0xe3,
	0x13, 0x96, 0x0d, 0xb3, 0x19, 0x3b, 0x99, 0x4d, 0x58, 0x42, 0xa3, 0xf8, 0x38, 0xa6, 0x23, 0xb7,
	0x81, 0xbb, 0xf0, 0x7c, 0x53, 0xf0, 0x61, 0x9a, 0xc5, 0x93, 0xf7, 0x2e, 0xc2, 0xfb, 0xf0, 0x62,
	0x93, 0xb1, 0x59, 0x14, 0x51, 0xc6, 0x5c, 0xe7, 0x31, 0xe3, 0xf1, 0x30, 0x1e, 0xd3, 0x91, 0xbb,
	0x85, 0x0f, 0xe0, 0xe5, 0x26, 0x8b, 0x86, 0x93, 0x88, 0x8e, 0x6f, 0x70, 0xf3, 0xb1, 0xbd, 0xf4,
	0x63, 0x12, 0xa7, 0x74, 0xe4, 0xb6, 0x70, 0x0f, 0xc8, 0xff, 0x90, 0x46, 0xb3, 0x8c, 0x8e, 0xdc,
	0xf6, 0x51, 0xf8, 0x6b, 0xe5, 0xa1, 0xab, 0x95, 0x87, 0xae, 0x57, 0x1e, 0xba, 0x5c, 0x7b, 0x8d,
	0xab, 0xb5, 0xd7, 0xf8, 0xbd, 0xf6, 0x1a, 0x9f, 0x9e, 0xdd, 0x9d, 0xd9, 0x85, 0x3d, 0x34, 0xf3,
	0xa3, 0x14, 0xfa, 0xb4, 0x6d, 0x9f, 0xe2, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x54,
	0x85, 0xe0, 0x86, 0x02, 0x00, 0x00,
}

func (m *Proposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.Expiration != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Expiration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Expiration):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintProposal(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x2a
	}
	if m.Warehouse != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Warehouse))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Proposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovProposal(uint64(m.Id))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.Warehouse != 0 {
		n += 1 + sovProposal(uint64(m.Warehouse))
	}
	if m.Expiration != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Expiration)
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovProposal(uint64(m.Status))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	return n
}

func sovProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposal(x uint64) (n int) {
	return sovProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Proposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Proposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Proposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Warehouse", wireType)
			}
			m.Warehouse = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Warehouse |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expiration == nil {
				m.Expiration = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Expiration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ProposalStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposal = fmt.Errorf("proto: unexpected end of group")
)
