name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go command
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
      - name: verify all
        run: make verify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
